### ISSUE TITLE
Issues regarding cluster compilation 

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcgmeta#5]
- [x] No CMake 3.13 was available with "GCCcore-6.4.0". Which is required for Libint2 from the cluster. Calling an up to dateCMake from a cluster directory returned "no permission" this was circumvent with a local Cmake install. 
- [x] static libcint install would not link (gqcp installation required shared object). This was fixed by installing libcint as .so.
- [x] Error in compilation of "gqcp/tests/units_test.cpp" : 
>/scratch/gent/425/vsc42536/apps/swalot/gqcg/gqcp/tests/units_test.cpp(31): error: more than one instance of overloaded function "std::abs" matches the argument list:
            function "abs(int)"
            function "std::abs(long)"
            function "std::abs(long long)"
            function "std::abs(__int128)"
            argument types are: (double)
      BOOST_CHECK(std::abs(GQCP::units::bohr_to_angstrom(1) - 0.529) < 1.0e-03);
      ^

Was fixed by adding `#include <cstdlib>
#include <cmath>` in a forked branch cluster_tm found at "https://github.com/tmhuysen/gqcp/tree/cluster_tm" (still puzzles me why this was an issue all of a sudden)
- [ ] Cannot use MKL because `find_package(BLAS REQUIRED)` 
- [ ] Some tests fail, example of error >unknown location(0): fatal error: in "h2o_sto3g_horton_plain": std::runtime_error: RHFSCFSolver::solve(): The RHF SCF procedure is converged but the MO Fock matrix is not diagonal.
/scratch/gent/425/vsc42536/apps/swalot/gqcg/gqcp/tests/RHF/PlainRHFSCFSolver_test.cpp(65): last checkpoint: "h2o_sto3g_horton_plain" test entry

possibly because i'm not linking MKL.

**Comment by guacke** [comment]
I am currently working on EasyBuild-configs for all dependencies. I will reference this issue when that PR is ready.
